### ISSUE TITLE
Handle cases where student or instructor mainnet account names are really really long.

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/near-certification-tools#14]
Consider asking Dan for ideas.

**Comment by ryancwalsh** [comment]
I wonder if https://stackoverflow.com/a/20552063/470749 would help.

**Comment by norrec99** [comment]
@ryancwalsh 
I've been working on this issue. I implemented the functionality from the stackoverflow you mentioned above. But I can't test it because the contract won't render the certs that have `accountName` which are 25 characters or longer. So for example we can render `rashaabdulrazzak.testnet` which has 24 characters but we can't render `rashaabdulrazzakr.testnet` because it is 1 character longer than previous one. 

Even though before I implemented the functionality from the stackoverflow, I couldn't render any cert that has a longer `accountName`. There is no problem about minting the certificate with a longer `accountName` but the problem is somewhere in the `web-app` I guess but I couldn't figure it out.

**Comment by norrec99** [comment]
Thanks to @rashaabdulrazzak and @ozanisgor we are now able to handle long names with a new function.

Here it looks like this
![image](https://user-images.githubusercontent.com/45902312/155367012-24a05df3-c5c0-4e58-ba4b-a8fc64723e72.png)

**Comment by ryancwalsh** [comment]
@norrec99 @ozanisgor @rashaabdulrazzak Good job figuring it out, team!

**Comment by ryancwalsh** [comment]
And good job with the helpful screenshots at https://github.com/NEAR-Edu/near-certification-tools/issues/14#issuecomment-1049007579 @norrec99
